spring:
  application:
    name: MK-Auth
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mk?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: lmk951010
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: 127.0.0.1


logging:
  level:
    com.mk.*: debug
    org.springframework.*: info
    org.springframework.security.*: debug


server:
  port: 18013