spring:
  application:
    name: cloud-auth-resources
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mk?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: lmk951010


auth-server-url: http://localhost:18003  # 授权服务地址

server:
  port: 18008
  servlet:
    session:
      cookie:
        name: UISESSIONMEMBER

security:
  oauth2:
    client:
      access-token-uri: ${auth-server-url}/oauth/token
      client-id: MiscorService
      client-secret: 123456
      scope: test
      user-authorization-uri: ${auth-server-url}/oauth/authorize
    resource:
      token-info-uri: ${auth-server-url}/oauth/check_token


logging:
  level:
    com.mk : debug
    org:
      springframework:
        web:
          debug
