spring:
  application:
    name: cloud-auth-resources


auth-server-url: http://localhost:18003  # 授权服务地址

server:
  port: 18008
  servlet:
    session:
      cookie:
        name: UISESSIONMEMBER

security:
  oauth2:
    client:
      access-token-uri: ${auth-server-url}/oauth/token
      client-id: MiscorService
      client-secret: 123456
      scope: test
      user-authorization-uri: ${auth-server-url}/oauth/authorize
    resource:
      token-info-uri: ${auth-server-url}/oauth/check_token


logging:
  level:
    com.mk : debug
    org:
      springframework:
        web:
          debug
