spring:
  application:
    name: cloud-auth-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mk?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: lmk951010



server:
  port: 18003

logging:
  level:
    com.mk.auth : debug
    org:
      springframework:
        web:
          debug
    
